name: Update and Commit

on:
  push:
    branches: [main]
  schedule:
    - cron: "30 0,3,7,11 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: |
          # python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update file
        run: |
          echo "${{ github.event_name }}"
          python currency.py > README.md
        env:
          KEY: ${{ secrets.KEY }}
          IV: ${{ secrets.IV }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          #git add .
          git commit -a -m "generated $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force
